cedir/uli

src/js/anestesista/components/LineasARA.js
src/js/anestesista/components/LineasNoARA.js

Algo de esto rompio el hot reloading, ya vere por que??

Cambios en vista Pago a Anestesista

---

src/js/estudio/api.js
src/js/estudio/components/EstudioDetailMain.js

Both were being saved as undefined when no content was added for them

Fix fields motivo and informe from estudio

---

src/js/comprobantes/components/FilterComprobante.js
src/js/comprobantes/components/ImporteForm.js

Se remueven comentarios y se agrega la posibilidad de colocar decimales en el importe

Fix para la creacion de comprobantes

---

src/js/presentaciones/modificar-presentacion/components/ModificarPresentacionPage.js

Bug report de belu: Modificar Presentacion no permite cambiar la fecha.

Se permite cambiar fecha en modificar presentacion

---

src/js/app/layout/components/Header.js
src/js/estudio/api.js

- Se agrega el parámetro sucursal en las llamadas a la api de estudios solo donde es necesario.
- Se agrega un texto al lado del botón de log out que indica en que sucursal esta iniciada la sesión.
Lista para mergear

Sucursal en estudios

---

src/js/estudio/components/ImportesEstudio.js
src/js/utilities/InputRF.js
src/js/utilities/constants.js
src/js/utilities/reduxFormValidators.js

- Se agrega en la pantalla de estudios un texto que indica el valor aproximado de la pension
- Se agrega al validator del dni la posibilidad de ingresar dni con 7 digitos
- Se agrega al validator que verifica los caracteres alfabéticos el alfabeto español para poder aceptar ñ y letras con tilde
Faltaría probarla en staging

Valor aproximado pension y filtros de estudio

---

.github/PULL_REQUEST_TEMPLATE
src/js/estudio/components/EstudioDetailMain.js

- Se agrega el numero de afiliado y su información extra del paciente en el texto que se muestra cuando pasas el mouse por el afiliado
- Aproveche y agregue el template para las pr de github 
Lista para el merge

Informacion extra paciente

---

package-lock.json
package.json
src/js/estudio/components/EstudioDetailPage.js
src/js/estudio/components/MedicacionEstudio.js
src/js/estudio/components/MedicacionEstudioTable.css
src/js/estudio/components/MedicacionEstudioTable.js

- Al momento de imprimir medicación se agregan los datos del paciente, la practica y la fecha
- Se modifican los estilos de impresión para poder utilizar la cabecera que se utiliza en el cedir
- Falta hablar con Belu para verificar si las medidas de la cabecera están bien
- Falta filtrar medicación y calcular bien el total (también hay que hablarlo con Belu)

Estudio: imprimir medicacion

---

package.json
src/js/estudio/components/MedicacionEstudio.js
src/js/estudio/components/MedicacionEstudioTable.css
src/js/estudio/components/MedicacionEstudioTable.js

- Se modifican los estilos de la impresion para que haya mas medicamentos en la misma hoja
- Se filtran los medicamentos de tipo Material Especifico ya que no se deberian imprimir ni sumar en la impresion
Lista para mergear

Imprimir medicacion p2

---

src/js/estudio/components/MedicacionEstudio.js
src/js/estudio/components/MedicacionEstudioTable.js

- Se arregla el problema que tenían las chicas que los cambios se cargaban en la pantalla y no se efectuaban en la impresión. El código esperaba una promesa en vez de una función, por lo que se adapta según los ejemplos de la libreria.
- Se extrae el comportamiento de filtrar medicación
- Testeado con las chicas y lista para mergear

Fix imprimir

---

src/js/comprobantes/api.js
src/js/comprobantes/components/crear-comprobante/ClienteForm.js
src/js/comprobantes/components/crear-comprobante/CreateComprobante.js
src/js/comprobantes/components/crear-comprobante/LineasForm.js
src/js/utilities/constants.js
src/js/utilities/reduxFormNormalizers.js
src/js/utilities/reduxFormValidators.js

- Se agregan validators para algunos campos
- Se remueve el campo tipo dni ya que no se utilizaba
- Se formatea el DNI cuando se ingresa
- Se corrige los campos que se envian en la llamada a la api.
- Se muestra el total del comprobante
Lista para mergear

Crear comprobante 2

---

src/js/comprobantes/components/ComprobanteRow.js
src/js/comprobantes/components/Comprobantes.js
src/js/comprobantes/components/crear-comprobante/BotonesForm.js
src/js/comprobantes/components/crear-comprobante/CreateComprobante.js
src/js/comprobantes/comprobantesEpic.js
src/js/comprobantes/comprobantesReducer.js
src/js/comprobantes/comprobantesReducuerInitialState.js

- Se agrega un checkbox para imprimir comprobantes
- Se agrega al listado de comprobantes una columna para imprimir comprobantes
Lista para mergear

Imprimir comprobantes

---

src/js/comprobantes/components/crear-comprobante/cliente-form/CamposCliente.js

- Se agrega el domicilio del paciente en el crear comprobantes
Lista

Crear comprobante: Domicilio paciente

---

src/js/anestesista/api.js

Se agrega sucursal en anestesistas
Lista

Sucursal en anestesistas

---

src/js/estudio/components/EstudioListTableRow.js
src/js/estudio/components/EstudiosActionBar.js
src/js/estudio/components/EstudiosDelDia.js
src/js/estudio/components/EstudiosList.js
src/js/estudio/components/EstudiosListTable.js
src/js/estudio/components/EstudiosTable.css
src/js/estudio/components/MedicacionEstudioTable.css
src/js/estudio/components/MedicacionEstudioTable.js
src/js/estudio/components/SearchEstudiosForm.js
src/js/estudio/components/SearchEstudiosModal.js

Se cambian varios componentes escritos en clases para poder utilizar la libreria react-to-print
Lista

Refactor en estudios

---

src/js/estudio/components/MedicacionEstudioTable.css

Qué cambios incorporas?
Está mergeable? Qué falta?

se aumenta el margen superior

---

src/js/estudio/components/MedicacionEstudioTable.css

Qué cambios incorporas?
Está mergeable? Qué falta?

Se solventa la impresion de una pagina en blanco

---

src/js/comprobantes/components/ComprobanteRow.js
src/js/comprobantes/components/crear-comprobante/BotonesForm.js
src/js/comprobantes/components/crear-comprobante/ComprobanteHandler.js
src/js/comprobantes/components/crear-comprobante/CreateComprobante.js
src/js/comprobantes/components/crear-comprobante/cabecera-form/CabeceraForm.js
src/js/comprobantes/components/crear-comprobante/cliente-form/ClienteForm.js
src/js/comprobantes/components/crear-comprobante/cliente-form/TipoClienteSelect.js
src/js/comprobantes/components/crear-comprobante/linea-form/LineasForm.js

- Se agrega una variable para hacer mas legible el codigo cuando se esta viendo un comprobante o cuando se esta editando
- Se guarda el porcentaje del iva en el estado
- Se saca el boton para ver el comprobante cuando no existe el cae
Listorti

Comprobantes refactor y quick fix

---

src/js/estudio/components/SearchEstudiosForm.js
src/js/estudio/components/search-estudios/FechaForm.js
src/js/estudio/components/search-estudios/MedicoForm.js
src/js/estudio/components/search-estudios/ObraSocialForm.js
src/js/estudio/components/search-estudios/PacienteForm.js

- Refactor en los filtros de estudios
Lista

Refactor filtro estudios

---

src/js/estudio/api.js
src/js/estudio/components/EstudioListTableRow.js
src/js/estudio/components/EstudiosListTable.js
src/js/estudio/components/SearchEstudiosForm.js
src/js/estudio/components/search-estudios/FechaForm.js
src/js/estudio/components/search-estudios/MedicoForm.js
src/js/estudio/components/search-estudios/PracticaForm.js

- Se agrega el filtro practica a estudios
- Se agrega un boton para eliminar la fecha del filtro
Lista

Filtro practica y fecha en estudios

---

src/js/estudio/components/EstudioDetailMain.js

- Se agrega un lapiz para enviar al admin y poder editar un paciente
Lista

Editar paciente en estudios

---

src/js/caja/components/CajaActionBar.js
src/js/caja/components/CajaMain.js
src/js/caja/components/ListadoMovimientosTable.js
src/js/caja/components/ListadoMovimientosTableRow.js

- Se hace refactor de algunos archivos de caja
Lista

Refactors caja

---

src/js/caja/api.js
src/js/caja/components/ListadoMovimientosTable.js
src/js/caja/components/search/SearchCajaForm.js
src/js/utilities/components/forms/PacienteField.js

- Se agrega el filtro paciente en caja y se hace reutilizable el campo Paciente
Lista

Filtro paciente en caja

---

src/js/caja/cajaSearchFormInitialState.js
src/js/caja/components/CajaActionBar.js
src/js/caja/components/CajaMain.js
src/js/caja/components/create/CreateCajaForm.js
src/js/caja/components/create/CreateMovimientosForm.js
src/js/caja/components/search/SearchCajaForm.js
src/js/estudio/estudioEpic.js
src/js/utilities/utilFunctions.js

- Se redondea el monto total
- La fecha de busqueda inicial es la actual
- Se destruye el formulario al hacer submit
Lista

Fix erroress caja

---

src/js/caja/cajaReducer.js

- Se borra del estado el estudio cuando se crea un movimiento
Lista

Asociar con estudio

---

src/js/caja/api.js
src/js/caja/cajaEpic.js
src/js/caja/cajaReducer.js
src/js/caja/cajaReducerInitialState.js
src/js/caja/components/CajaMain.js
src/js/caja/components/CajaTableView.js
src/js/caja/components/ListadoMovimientosTable.js
src/js/caja/components/ListadoMovimientosTableHeader.js
src/js/caja/components/search/SearchCajaForm.js
src/js/utilities/components/ThIcon.js

- Se crea un componente para poner un th con iconos de flechas que se intercambian en cada click.
- Se envia el campo por el cual se deben ordenar los movimientos
- Se permite apretar los titulos de las columnas para ordenar los movimientos.
- Se borran los campos una vez cerrado el formulario de buscar movimientos
Lista.

Cambios en caja

---

src/js/comprobantes/components/crear-comprobante/BotonesForm.js
src/js/comprobantes/components/crear-comprobante/ConfirmationModal.js
src/js/comprobantes/components/crear-comprobante/CreateComprobante.js
src/js/comprobantes/components/crear-comprobante/cliente-form/CamposCliente.js
src/js/comprobantes/components/crear-comprobante/cliente-form/ClienteForm.js
src/js/utilities/components/forms/ObraSocialField.js
src/js/utilities/components/forms/PacienteField.js

- Se crea un field de obra social reutilizable
- Se cambia el field nombre cliente para usar los campos reutilizables
Lista

Fix crear comprobantes

---

cypress/integration/ComprobanteTest.js
cypress/support/commands.js
src/js/comprobantes/api.js
src/js/comprobantes/components/ComprobanteRow.js
src/js/comprobantes/components/Comprobantes.js
src/js/comprobantes/components/ImporteComprobanteAsociado.js
src/js/comprobantes/components/ImporteForm.js
src/js/comprobantes/components/comprobante-asociado/ComprobanteAsociadoFields.js
src/js/comprobantes/components/comprobante-asociado/ComprobanteAsociadoFooter.js
src/js/comprobantes/components/comprobante-asociado/ComprobanteAsociadoForm.js
src/js/comprobantes/components/comprobante-asociado/ComprobanteAsociadoModal.js
src/js/comprobantes/components/crear-comprobante/CreateComprobante.js
src/js/comprobantes/components/crear-comprobante/cabecera-form/CabeceraForm.js
src/js/comprobantes/comprobantesEpic.js
src/js/comprobantes/comprobantesReducer.js
src/js/presentaciones/cobrar-presentacion/components/toolbar/ModalHandler.js
src/js/utilities/generalUtilities.js
src/js/utilities/reduxFormNormalizers.js

- Se agregan dos campos a crear el comprobante asociado
- Se renueva el formulario de crear comprobante asociado
- Se cambia el icono
- Se agregan test sobre lo existente de comprobante asociado y sobre lo nuevo
Lista

Comprobante asociado iva y tipo

---

src/js/estudio/api.js
src/js/estudio/components/EstudioListTableRow.js
src/js/estudio/components/EstudiosActionBar.js
src/js/estudio/components/EstudiosDelDia.js
src/js/estudio/components/EstudiosList.js
src/js/estudio/components/EstudiosListTable.js
src/js/estudio/components/EstudiosTable.css

- Se borra el imprimir de estudios del frontend
- Se llama al backend para imprimir estudios
Lista

Imprimir estudios

---

cypress/integration/EstudioTest.js
cypress/support/commands.js

- Se agregan tests para estudios
Lista

Init test estudios
